import type { IncomingMessage, ServerResponse } from 'node:http';
import type { PrismaClient } from '@prisma/client';
import { canResolveInbox, classifyInboxMessage, inboxSlaState } from '../../api/src/inbox-workflow';

type StaffAccount = { current: { userId: string }; membership: { role: string } };
type OwnerAccount = { current: { userId: string }; owner: { id: string; telegramUserId: string | null } };
type Context = { request: IncomingMessage; response: ServerResponse; url: URL; db: PrismaClient; organizationId: string; currentStaff(request: IncomingMessage): Promise<StaffAccount | undefined>; currentOwner(request: IncomingMessage): Promise<OwnerAccount | undefined>; body(request: IncomingMessage): Promise<string>; json(response: ServerResponse, status: number, payload: unknown): void; idempotencyKey(request: IncomingMessage): string | undefined; audit(input: { actorId: string; action: string; aggregateType: string; aggregateId: string; idempotencyKey: string; payload?: Record<string, unknown> }): Promise<void>; sendTelegram?(chatId: string, text: string): Promise<unknown> };
const clean = (value: unknown, limit = 5000) => String(value ?? '').trim().slice(0, limit);
const inboxRoles = ['ADMIN', 'MANAGER', 'RECEPTIONIST', 'VETERINARIAN', 'GROOMER'];

export async function ingestInboxMessage(input: { db: PrismaClient; organizationId: string; ownerId: string; petId?: string; threadId?: string; source: string; channel: string; body: string; externalKey?: string; externalMessageId?: string; idempotencyKey: string }) {
  const signal = classifyInboxMessage(input.body); const subject = input.body.split(/[.!?\n]/)[0].slice(0, 120) || 'Новое обращение';
  return input.db.$transaction(async (tx) => {
    let thread = input.threadId ? await tx.inboxThread.findFirst({ where: { id: input.threadId, organizationId: input.organizationId, ownerId: input.ownerId } }) : input.externalKey ? await tx.inboxThread.findUnique({ where: { externalKey: input.externalKey } }) : null;
    if (thread?.state === 'RESOLVED' && input.externalKey) { await tx.inboxThread.update({ where: { id: thread.id }, data: { externalKey: null } }); thread = null; }
    if (!thread) thread = await tx.inboxThread.create({ data: { organizationId: input.organizationId, ownerId: input.ownerId, petId: input.petId, subject, source: input.source, classification: signal.classification, priority: signal.priority, state: 'OPEN', assignedRole: signal.assignedRole, slaDueAt: signal.slaDueAt, externalKey: input.externalKey, idempotencyKey: `${input.idempotencyKey}:thread` } });
    else thread = await tx.inboxThread.update({ where: { id: thread.id }, data: { state: thread.assigneeId ? 'ASSIGNED' : 'OPEN', classification: signal.classification === 'URGENT' ? signal.classification : thread.classification, priority: signal.priority === 'CRITICAL' ? signal.priority : thread.priority, slaDueAt: signal.priority === 'CRITICAL' ? signal.slaDueAt : thread.slaDueAt } });
    const message = await tx.inboxMessage.upsert({ where: { idempotencyKey: input.idempotencyKey }, update: {}, create: { organizationId: input.organizationId, threadId: thread.id, authorType: 'OWNER', authorId: input.ownerId, direction: 'INBOUND', channel: input.channel, body: input.body, externalMessageId: input.externalMessageId, idempotencyKey: input.idempotencyKey } });
    await tx.communicationLog.upsert({ where: { idempotencyKey: `${input.idempotencyKey}:communication` }, update: {}, create: { organizationId: input.organizationId, ownerId: input.ownerId, petId: input.petId, channel: input.channel, direction: 'INBOUND', kind: signal.classification, subject, body: input.body, state: 'LOGGED', externalMessageId: input.externalMessageId, idempotencyKey: `${input.idempotencyKey}:communication` } });
    return { thread, message, signal };
  });
}

export async function handleInboxRoutes(ctx: Context): Promise<boolean> {
  const { request, response, url, db, organizationId } = ctx;
  if (request.method === 'GET' && url.pathname === '/api/v1/client/inbox') {
    const account = await ctx.currentOwner(request); if (!account) { ctx.json(response, 401, { error: 'UNAUTHORIZED' }); return true; }
    const threads = await db.inboxThread.findMany({ where: { organizationId, ownerId: account.owner.id }, include: { messages: { orderBy: { createdAt: 'asc' }, take: 200 } }, orderBy: { updatedAt: 'desc' }, take: 50 });
    ctx.json(response, 200, { threads: threads.map((thread) => ({ ...thread, slaState: inboxSlaState(thread.slaDueAt, thread.state) })) }); return true;
  }
  if (request.method === 'POST' && url.pathname === '/api/v1/client/inbox/threads') {
    const account = await ctx.currentOwner(request); const key = ctx.idempotencyKey(request); if (!account) { ctx.json(response, 401, { error: 'UNAUTHORIZED' }); return true; } if (!key) { ctx.json(response, 400, { error: 'IDEMPOTENCY_KEY_REQUIRED' }); return true; }
    const repeated = await db.inboxThread.findUnique({ where: { idempotencyKey: `${key}:thread` }, include: { messages: true } }); if (repeated) { ctx.json(response, 200, { thread: repeated }); return true; }
    let input: Record<string, unknown>; try { input = JSON.parse(await ctx.body(request)); } catch { ctx.json(response, 400, { error: 'INVALID_REQUEST' }); return true; }
    const message = clean(input.message, 5000); const petId = clean(input.petId, 80) || undefined; if (message.length < 3) { ctx.json(response, 400, { error: 'MESSAGE_REQUIRED' }); return true; }
    if (petId && !await db.ownerPetRelation.findFirst({ where: { organizationId, ownerId: account.owner.id, petId, state: 'ACTIVE' } })) { ctx.json(response, 403, { error: 'PET_ACCESS_REQUIRED' }); return true; }
    const result = await ingestInboxMessage({ db, organizationId, ownerId: account.owner.id, petId, source: 'CLIENT_APP', channel: 'IN_APP', body: message, idempotencyKey: key });
    await ctx.audit({ actorId: account.current.userId, action: 'inbox.thread_created', aggregateType: 'InboxThread', aggregateId: result.thread.id, idempotencyKey: key, payload: { classification: result.signal.classification, priority: result.signal.priority } });
    ctx.json(response, 201, { thread: result.thread, emergencyNotice: result.signal.emergencyNotice }); return true;
  }
  const clientMessage = url.pathname.match(/^\/api\/v1\/client\/inbox\/threads\/([^/]+)\/messages$/);
  if (request.method === 'POST' && clientMessage) {
    const account = await ctx.currentOwner(request); const key = ctx.idempotencyKey(request); if (!account) { ctx.json(response, 401, { error: 'UNAUTHORIZED' }); return true; } if (!key) { ctx.json(response, 400, { error: 'IDEMPOTENCY_KEY_REQUIRED' }); return true; }
    const thread = await db.inboxThread.findFirst({ where: { id: decodeURIComponent(clientMessage[1]), organizationId, ownerId: account.owner.id } }); if (!thread) { ctx.json(response, 404, { error: 'NOT_FOUND' }); return true; }
    let input: Record<string, unknown>; try { input = JSON.parse(await ctx.body(request)); } catch { ctx.json(response, 400, { error: 'INVALID_REQUEST' }); return true; } const message = clean(input.message, 5000); if (message.length < 1) { ctx.json(response, 400, { error: 'MESSAGE_REQUIRED' }); return true; }
    const result = await ingestInboxMessage({ db, organizationId, ownerId: account.owner.id, petId: thread.petId ?? undefined, threadId: thread.id, source: thread.source, channel: 'IN_APP', body: message, externalKey: thread.externalKey ?? undefined, idempotencyKey: key });
    await ctx.audit({ actorId: account.current.userId, action: 'inbox.owner_replied', aggregateType: 'InboxThread', aggregateId: result.thread.id, idempotencyKey: key, payload: { classification: result.signal.classification } }); ctx.json(response, 201, { thread: result.thread }); return true;
  }
  if (request.method === 'GET' && url.pathname === '/api/v1/staff/inbox') {
    const staff = await ctx.currentStaff(request); if (!staff) { ctx.json(response, 401, { error: 'UNAUTHORIZED' }); return true; } if (!inboxRoles.includes(staff.membership.role)) { ctx.json(response, 403, { error: 'INBOX_ROLE_REQUIRED' }); return true; }
    const state = clean(url.searchParams.get('state'), 30).toUpperCase(); const cursor = clean(url.searchParams.get('cursor'), 80); const threads = await db.inboxThread.findMany({ where: { organizationId, ...(state && state !== 'ALL' ? { state } : {}) }, include: { messages: { orderBy: { createdAt: 'asc' }, take: 200 } }, orderBy: [{ priority: 'asc' }, { slaDueAt: 'asc' }, { updatedAt: 'desc' }], take: 51, ...(cursor ? { cursor: { id: cursor }, skip: 1 } : {}) });
    const page = threads.slice(0, 50); const owners = await db.owner.findMany({ where: { organizationId, id: { in: page.map((item) => item.ownerId) } } }); const pets = await db.pet.findMany({ where: { organizationId, id: { in: page.flatMap((item) => item.petId ? [item.petId] : []) } } }); const ownerById = new Map(owners.map((item) => [item.id, item])); const petById = new Map(pets.map((item) => [item.id, item]));
    ctx.json(response, 200, { role: staff.membership.role, threads: page.map((thread) => ({ ...thread, owner: ownerById.get(thread.ownerId), pet: thread.petId ? petById.get(thread.petId) : null, slaState: inboxSlaState(thread.slaDueAt, thread.state) })), nextCursor: threads.length > 50 ? page.at(-1)?.id : null }); return true;
  }
  const staffThread = url.pathname.match(/^\/api\/v1\/staff\/inbox\/threads\/([^/]+)$/);
  if (request.method !== 'PATCH' || !staffThread) return false;
  const staff = await ctx.currentStaff(request); const key = ctx.idempotencyKey(request); if (!staff) { ctx.json(response, 401, { error: 'UNAUTHORIZED' }); return true; } if (!inboxRoles.includes(staff.membership.role)) { ctx.json(response, 403, { error: 'INBOX_ROLE_REQUIRED' }); return true; } if (!key) { ctx.json(response, 400, { error: 'IDEMPOTENCY_KEY_REQUIRED' }); return true; }
  const thread = await db.inboxThread.findFirst({ where: { id: decodeURIComponent(staffThread[1]), organizationId }, include: { messages: true } }); if (!thread) { ctx.json(response, 404, { error: 'NOT_FOUND' }); return true; }
  let input: Record<string, unknown>; try { input = JSON.parse(await ctx.body(request)); } catch { ctx.json(response, 400, { error: 'INVALID_REQUEST' }); return true; } const action = clean(input.action, 30).toUpperCase();
  if (action === 'ASSIGN') { const assigneeId = clean(input.assigneeId, 80) || staff.current.userId; const membership = await db.staffMembership.findFirst({ where: { organizationId, userId: assigneeId, state: 'ACTIVE' } }); if (!membership) { ctx.json(response, 400, { error: 'ACTIVE_ASSIGNEE_REQUIRED' }); return true; } const updated = await db.inboxThread.update({ where: { id: thread.id }, data: { assigneeId, assignedRole: membership.role, state: 'ASSIGNED' } }); await ctx.audit({ actorId: staff.current.userId, action: 'inbox.assigned', aggregateType: 'InboxThread', aggregateId: thread.id, idempotencyKey: key, payload: { assigneeId } }); ctx.json(response, 200, { thread: updated }); return true; }
  if (action === 'CLASSIFY') { const classification = clean(input.classification, 40).toUpperCase(); if (!['ADMINISTRATIVE', 'PROFESSIONAL', 'URGENT'].includes(classification)) { ctx.json(response, 400, { error: 'INVALID_CLASSIFICATION' }); return true; } const signal = classifyInboxMessage(classification === 'URGENT' ? 'не дышит' : classification === 'PROFESSIONAL' ? 'симптом' : 'вопрос'); const updated = await db.inboxThread.update({ where: { id: thread.id }, data: { classification, priority: signal.priority, assignedRole: signal.assignedRole, slaDueAt: signal.slaDueAt } }); await ctx.audit({ actorId: staff.current.userId, action: 'inbox.classified', aggregateType: 'InboxThread', aggregateId: thread.id, idempotencyKey: key, payload: { classification } }); ctx.json(response, 200, { thread: updated }); return true; }
  if (action === 'REPLY') { const message = clean(input.message, 5000); if (message.length < 1 || thread.state === 'RESOLVED') { ctx.json(response, 409, { error: 'THREAD_NOT_REPLYABLE' }); return true; } const owner = await db.owner.findFirst({ where: { id: thread.ownerId, organizationId } }); const conversation = owner?.telegramUserId ? await db.telegramConversation.findUnique({ where: { organizationId_telegramUserId: { organizationId, telegramUserId: owner.telegramUserId } } }) : null; const created = await db.$transaction(async (tx) => { const reply = await tx.inboxMessage.create({ data: { organizationId, threadId: thread.id, authorType: 'STAFF', authorId: staff.current.userId, direction: 'OUTBOUND', channel: conversation ? 'TELEGRAM' : 'IN_APP', body: message, idempotencyKey: key } }); const updated = await tx.inboxThread.update({ where: { id: thread.id }, data: { assigneeId: thread.assigneeId ?? staff.current.userId, assignedRole: thread.assignedRole ?? staff.membership.role, state: 'WAITING_OWNER', firstResponseAt: thread.firstResponseAt ?? new Date() } }); await tx.communicationLog.create({ data: { organizationId, ownerId: thread.ownerId, petId: thread.petId, channel: conversation ? 'TELEGRAM' : 'IN_APP', direction: 'OUTBOUND', kind: thread.classification, subject: thread.subject, body: message, state: conversation ? 'SENT' : 'LOGGED', staffId: staff.current.userId, idempotencyKey: `${key}:communication` } }); return { reply, updated, conversation }; }); if (created.conversation && ctx.sendTelegram) await ctx.sendTelegram(created.conversation.chatId, message).catch(() => undefined); await ctx.audit({ actorId: staff.current.userId, action: 'inbox.replied', aggregateType: 'InboxThread', aggregateId: thread.id, idempotencyKey: key, payload: { channel: created.conversation ? 'TELEGRAM' : 'IN_APP' } }); ctx.json(response, 200, { thread: created.updated, message: created.reply }); return true; }
  if (action === 'RESOLVE') { const outcome = clean(input.outcome, 3000); if (!canResolveInbox(thread.state, outcome)) { ctx.json(response, 409, { error: 'OUTCOME_REQUIRED' }); return true; } const followUpAt = input.followUpAt ? new Date(clean(input.followUpAt, 80)) : null; if (followUpAt && (Number.isNaN(followUpAt.valueOf()) || followUpAt <= new Date())) { ctx.json(response, 400, { error: 'INVALID_FOLLOW_UP_DATE' }); return true; } const updated = await db.$transaction(async (tx) => { const result = await tx.inboxThread.update({ where: { id: thread.id }, data: { state: 'RESOLVED', outcome, resolvedAt: new Date(), followUpAt } }); if (followUpAt) await tx.operationalTask.create({ data: { organizationId, title: `Follow-up: ${thread.subject}`, kind: 'INBOX_FOLLOW_UP', priority: thread.priority, state: 'OPEN', assigneeId: thread.assigneeId ?? staff.current.userId, ownerId: thread.ownerId, petId: thread.petId, dueAt: followUpAt, details: outcome, relatedType: 'INBOX_THREAD', relatedId: thread.id, idempotencyKey: `${key}:follow-up` } }); return result; }); await ctx.audit({ actorId: staff.current.userId, action: 'inbox.resolved', aggregateType: 'InboxThread', aggregateId: thread.id, idempotencyKey: key, payload: { outcome, followUpAt: followUpAt?.toISOString() } }); ctx.json(response, 200, { thread: updated }); return true; }
  if (action === 'REOPEN') { if (thread.state !== 'RESOLVED') { ctx.json(response, 409, { error: 'THREAD_NOT_RESOLVED' }); return true; } const signal = classifyInboxMessage(thread.subject); const updated = await db.inboxThread.update({ where: { id: thread.id }, data: { state: 'OPEN', outcome: null, resolvedAt: null, slaDueAt: signal.slaDueAt } }); await ctx.audit({ actorId: staff.current.userId, action: 'inbox.reopened', aggregateType: 'InboxThread', aggregateId: thread.id, idempotencyKey: key }); ctx.json(response, 200, { thread: updated }); return true; }
  ctx.json(response, 400, { error: 'UNKNOWN_INBOX_ACTION' }); return true;
}
