import { randomUUID } from 'node:crypto';
import { DomainError } from '../core/errors';
import type { CommandMeta, ISODateTime, UUID } from '../core/types';
import { iso } from '../core/types';
import { AccessService } from '../identity/access-service';
import { PhysicalIdentityService } from '../identity/physical-identity-service';
import { AuditOutbox } from '../platform/audit-outbox';
import { DiagnosticService } from './diagnostic-service';

export type SpecimenState = 'COLLECTED' | 'IN_TRANSIT' | 'RECEIVED' | 'REJECTED' | 'RESULT_LINKED';
export type Specimen = { id: UUID; organizationId: UUID; orderId: UUID; petId: UUID; type: string; container: string; state: SpecimenState; collectedBy: UUID; collectedAt: ISODateTime; location?: string; externalReference?: string; receivedAt?: ISODateTime; rejectedReason?: string; resultLinkedAt?: ISODateTime; identityId: UUID };
export type SpecimenLabel = { opaqueToken: string; specimenReference: string; patientShortIdentity: string; collectedAt: ISODateTime; type: string };

/** Chain of custody records each hand-off; a result cannot be linked to a rejected or unreceived specimen. */
export class SpecimenService {
  readonly specimens = new Map<UUID, Specimen>();
  constructor(private readonly journal: AuditOutbox, private readonly access: AccessService, private readonly diagnostics: DiagnosticService, private readonly identities: PhysicalIdentityService) {}
  collect(input: { orderId: UUID; type: string; container: string; location?: string }, meta: CommandMeta): Specimen {
    this.access.require(meta.actor, 'clinical:write'); const order = this.diagnostics.orders.get(input.orderId); if (!order || order.organizationId !== meta.actor.organizationId) throw new DomainError('NOT_FOUND', 'Diagnostic order is not available.'); if (order.state !== 'ORDERED' || !input.type.trim() || !input.container.trim()) throw new DomainError('CONFLICT', 'An ordered test, specimen type and container are required.');
    this.diagnostics.collect(order.id, { ...meta, idempotencyKey: `${meta.idempotencyKey}:lab-order` }); const now = meta.now ?? new Date(); const specimenBaseId = randomUUID(); const identity = this.identities.issue({ targetType: 'SPECIMEN', targetId: specimenBaseId }, meta); const specimen: Specimen = { id: specimenBaseId, organizationId: meta.actor.organizationId, orderId: order.id, petId: order.petId, type: input.type.trim(), container: input.container.trim(), state: 'COLLECTED', collectedBy: meta.actor.userId, collectedAt: iso(now), location: input.location?.trim() || undefined, identityId: identity.id }; this.specimens.set(specimen.id, specimen); this.record(meta, specimen, 'specimen.collected', { container: specimen.container }, now); return specimen;
  }
  sendExternal(specimenId: UUID, input: { location: string; externalReference: string }, meta: CommandMeta): Specimen { this.access.require(meta.actor, 'clinical:write'); const specimen = this.get(specimenId, meta.actor.organizationId); if (specimen.state !== 'COLLECTED' || !input.location.trim() || !input.externalReference.trim()) throw new DomainError('CONFLICT', 'Only a collected specimen can be sent with a destination and external reference.'); specimen.state = 'IN_TRANSIT'; specimen.location = input.location.trim(); specimen.externalReference = input.externalReference.trim(); this.record(meta, specimen, 'specimen.sent_external', {}); return specimen; }
  receive(specimenId: UUID, location: string, meta: CommandMeta): Specimen { this.access.require(meta.actor, 'clinical:write'); const specimen = this.get(specimenId, meta.actor.organizationId); if (specimen.state !== 'IN_TRANSIT' || !location.trim()) throw new DomainError('CONFLICT', 'Only an in-transit specimen can be received.'); const now = meta.now ?? new Date(); specimen.state = 'RECEIVED'; specimen.location = location.trim(); specimen.receivedAt = iso(now); this.record(meta, specimen, 'specimen.received', {}, now); return specimen; }
  reject(specimenId: UUID, reason: string, meta: CommandMeta): Specimen { this.access.require(meta.actor, 'clinical:write'); const specimen = this.get(specimenId, meta.actor.organizationId); if (!['COLLECTED', 'IN_TRANSIT', 'RECEIVED'].includes(specimen.state) || !reason.trim()) throw new DomainError('CONFLICT', 'An active specimen and rejection reason are required.'); specimen.state = 'REJECTED'; specimen.rejectedReason = reason.trim(); this.record(meta, specimen, 'specimen.rejected', {}); return specimen; }
  linkResult(specimenId: UUID, summary: string, meta: CommandMeta): Specimen { this.access.require(meta.actor, 'clinical:write'); const specimen = this.get(specimenId, meta.actor.organizationId); if (specimen.state !== 'RECEIVED' || !summary.trim()) throw new DomainError('CONFLICT', 'Only a received specimen can receive a result.'); this.diagnostics.result(specimen.orderId, summary, { ...meta, idempotencyKey: `${meta.idempotencyKey}:lab-result` }); specimen.state = 'RESULT_LINKED'; specimen.resultLinkedAt = iso(meta.now ?? new Date()); this.record(meta, specimen, 'specimen.result_linked', {}); return specimen; }
  label(specimenId: UUID, organizationId: UUID): SpecimenLabel { const specimen = this.get(specimenId, organizationId); const identity = this.identities.identities.get(specimen.identityId); if (!identity || identity.state !== 'ACTIVE') throw new DomainError('CONFLICT', 'An active opaque specimen label is required.'); return { opaqueToken: identity.opaqueToken, specimenReference: `S-${specimen.id.slice(0, 8).toUpperCase()}`, patientShortIdentity: `P-${specimen.petId.slice(0, 6).toUpperCase()}`, collectedAt: specimen.collectedAt, type: specimen.type }; }
  private get(specimenId: UUID, organizationId: UUID): Specimen { const specimen = this.specimens.get(specimenId); if (!specimen || specimen.organizationId !== organizationId) throw new DomainError('NOT_FOUND', 'Specimen is not available in this organization.'); return specimen; }
  private record(meta: CommandMeta, specimen: Specimen, action: string, metadata: Record<string, unknown>, now = meta.now ?? new Date()): void { this.journal.record(meta, { action, aggregateType: 'Specimen', aggregateId: specimen.id, metadata }, { eventName: action, aggregateType: 'Specimen', aggregateId: specimen.id, payload: { petId: specimen.petId, orderId: specimen.orderId } }, now); }
}
