import { randomUUID } from 'node:crypto';
import { DomainError } from '../core/errors';
import type { CommandMeta, ISODateTime, UUID } from '../core/types';
import { iso } from '../core/types';
import { AccessService } from '../identity/access-service';
import { AuditOutbox } from '../platform/audit-outbox';

export type ChecklistTemplate = { id: UUID; organizationId: UUID; purpose: string; version: number; state: 'DRAFT' | 'PUBLISHED'; steps: Array<{ key: string; label: string; required: boolean; evidenceRequired: boolean }>; createdAt: ISODateTime };
export type ChecklistRun = { id: UUID; organizationId: UUID; templateId: UUID; targetType: string; targetId: UUID; state: 'OPEN' | 'SIGNED_OFF'; steps: Array<{ key: string; completed: boolean; evidence?: string; completedBy?: UUID; completedAt?: ISODateTime }>; signedOffBy?: UUID; signedOffAt?: ISODateTime; createdAt: ISODateTime };

export class ChecklistService {
  readonly templates = new Map<UUID, ChecklistTemplate>(); readonly runs = new Map<UUID, ChecklistRun>();
  constructor(private readonly journal: AuditOutbox, private readonly access: AccessService) {}
  createTemplate(input: { purpose: string; steps: ChecklistTemplate['steps'] }, meta: CommandMeta): ChecklistTemplate { this.access.require(meta.actor, 'organization:manage'); if (!input.purpose.trim() || !input.steps.length || input.steps.some((step) => !step.key.trim() || !step.label.trim())) throw new DomainError('VALIDATION', 'Purpose and named checklist steps are required.'); const version = Math.max(0, ...[...this.templates.values()].filter((item) => item.organizationId === meta.actor.organizationId && item.purpose === input.purpose.trim()).map((item) => item.version)) + 1; const now = meta.now ?? new Date(); const template: ChecklistTemplate = { id: randomUUID(), organizationId: meta.actor.organizationId, purpose: input.purpose.trim(), version, state: 'DRAFT', steps: input.steps.map((step) => ({ ...step, key: step.key.trim(), label: step.label.trim() })), createdAt: iso(now) }; this.templates.set(template.id, template); return template; }
  publish(templateId: UUID, meta: CommandMeta): ChecklistTemplate { this.access.require(meta.actor, 'organization:manage'); const template = this.template(templateId, meta.actor.organizationId); if (template.state !== 'DRAFT') throw new DomainError('CONFLICT', 'Only a draft checklist template can be published.'); template.state = 'PUBLISHED'; return template; }
  start(input: { templateId: UUID; targetType: string; targetId: UUID }, meta: CommandMeta): ChecklistRun { this.access.require(meta.actor, 'clinical:write'); const template = this.template(input.templateId, meta.actor.organizationId); if (template.state !== 'PUBLISHED' || !input.targetType.trim() || !input.targetId.trim()) throw new DomainError('CONFLICT', 'A published template and explicit target are required.'); const now = meta.now ?? new Date(); const run: ChecklistRun = { id: randomUUID(), organizationId: meta.actor.organizationId, templateId: template.id, targetType: input.targetType.trim(), targetId: input.targetId, state: 'OPEN', steps: template.steps.map((step) => ({ key: step.key, completed: false })), createdAt: iso(now) }; this.runs.set(run.id, run); this.record(meta, run, 'checklist.started', {}, now); return run; }
  completeStep(runId: UUID, key: string, evidence: string | undefined, meta: CommandMeta): ChecklistRun { this.access.require(meta.actor, 'clinical:write'); const run = this.run(runId, meta.actor.organizationId); const template = this.template(run.templateId, run.organizationId); const definition = template.steps.find((step) => step.key === key); const step = run.steps.find((item) => item.key === key); if (run.state !== 'OPEN' || !definition || !step || (definition.evidenceRequired && !evidence?.trim())) throw new DomainError('CONFLICT', 'An open checklist step and required evidence are needed.'); const now = meta.now ?? new Date(); step.completed = true; step.evidence = evidence?.trim() || undefined; step.completedBy = meta.actor.userId; step.completedAt = iso(now); this.record(meta, run, 'checklist.step_completed', { key }, now); return run; }
  signOff(runId: UUID, meta: CommandMeta): ChecklistRun { this.access.require(meta.actor, 'clinical:write'); const run = this.run(runId, meta.actor.organizationId); const template = this.template(run.templateId, run.organizationId); if (run.state !== 'OPEN' || template.steps.some((definition) => definition.required && !run.steps.find((step) => step.key === definition.key)?.completed)) throw new DomainError('CONFLICT', 'All required checklist steps must be completed before sign-off.'); const now = meta.now ?? new Date(); run.state = 'SIGNED_OFF'; run.signedOffBy = meta.actor.userId; run.signedOffAt = iso(now); this.record(meta, run, 'checklist.signed_off', {}, now); return run; }
  private template(id: UUID, organizationId: UUID): ChecklistTemplate { const item = this.templates.get(id); if (!item || item.organizationId !== organizationId) throw new DomainError('NOT_FOUND', 'Checklist template is not available.'); return item; }
  private run(id: UUID, organizationId: UUID): ChecklistRun { const item = this.runs.get(id); if (!item || item.organizationId !== organizationId) throw new DomainError('NOT_FOUND', 'Checklist run is not available.'); return item; }
  private record(meta: CommandMeta, run: ChecklistRun, action: string, metadata: Record<string, unknown>, now = meta.now ?? new Date()): void { this.journal.record(meta, { action, aggregateType: 'ChecklistRun', aggregateId: run.id, metadata }, { eventName: action, aggregateType: 'ChecklistRun', aggregateId: run.id, payload: { targetType: run.targetType, targetId: run.targetId } }, now); }
}
