const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const state={catalog:null,selected:null};
const dateKey=(date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Moscow',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
const formatTime=(value)=>new Date(value).toLocaleTimeString('ru-RU',{timeZone:'Europe/Moscow',hour:'2-digit',minute:'2-digit'});
const form=$('#grooming-booking'),variant=form.elements.variantId,locationField=form.elements.locationId,dateField=form.elements.date,startsAt=form.elements.startsAt,slots=$('#slots'),choice=$('#choice'),submit=form.querySelector('[type=submit]');
dateField.min=dateKey(new Date());dateField.value=dateKey(new Date(Date.now()+86400000));
async function api(path){const response=await fetch(path,{headers:{accept:'application/json'}});const data=await response.json();if(!response.ok)throw Error(data.error||'Не удалось загрузить данные');return data}
function chooseService(id){variant.value=id;$('#booking').scrollIntoView({behavior:'smooth'});loadSlots()}
async function loadCatalog(){try{state.catalog=await api('/api/v1/public/grooming/catalog');variant.innerHTML='<option value="">Выберите вариант</option>'+state.catalog.variants.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');locationField.innerHTML='<option value="">Выберите локацию</option>'+state.catalog.locations.map(x=>`<option value="${x.id}">${x.name}</option>`).join('');if(state.catalog.locations.length===1)locationField.value=state.catalog.locations[0].id;const descriptions=['Мягкое знакомство, диагностика шерсти и персональный маршрут без спешки.','Полный цикл ухода с сохранением рецепта, реакции питомца и рекомендаций.','Поддерживающий уход между большими визитами — аккуратно и предсказуемо.'];$('#service-list').innerHTML=state.catalog.variants.map((x,i)=>`<article class="service-card"><span class="number">0${i+1} · ${x.durationMinutes} МИН</span><button type="button" data-service="${x.id}" aria-label="Выбрать ${x.name}">↘</button><h3>${x.name}</h3><p>${descriptions[i%descriptions.length]}</p><div class="service-meta"><span>${x.allowedSpecies.includes('CAT')?'кошки и собаки':'для собак'}</span><b>${x.priceMinor?`${(x.priceMinor/100).toLocaleString('ru-RU')} ₽`:'расчёт после знакомства'}</b></div></article>`).join('');$$('[data-service]').forEach(b=>b.onclick=()=>chooseService(b.dataset.service))}catch{$('#service-list').innerHTML='<article class="service-card"><h3>Маршрут ухода</h3><p>Расписание временно обновляется. Откройте кабинет — команда поможет выбрать окно.</p></article>'}}
async function loadSlots(){startsAt.value='';choice.hidden=true;submit.disabled=true;if(!variant.value||!locationField.value||!dateField.value){slots.innerHTML='<span>Выберите уход, локацию и день.</span>';return}slots.innerHTML='<span>Сверяем живое расписание…</span>';try{const result=await api(`/api/v1/public/grooming/availability?variantId=${encodeURIComponent(variant.value)}&locationId=${encodeURIComponent(locationField.value)}&date=${encodeURIComponent(dateField.value)}`);slots.innerHTML=result.slots.length?result.slots.map(x=>`<button type="button" data-start="${x.startsAt}"><b>${formatTime(x.startsAt)}</b><small>${x.available>1?`${x.available} места`:'последнее'}</small></button>`).join(''):'<span>На этот день окна закончились. Выберите соседнюю дату — после входа будет доступен лист ожидания.</span>';$$('[data-start]',slots).forEach(button=>button.onclick=()=>{$$('button',slots).forEach(x=>x.classList.toggle('active',x===button));startsAt.value=button.dataset.start;state.selected=button.dataset.start;choice.hidden=false;choice.textContent=`Выбрано: ${new Date(state.selected).toLocaleString('ru-RU',{timeZone:'Europe/Moscow',weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}`;submit.disabled=false})}catch(error){slots.innerHTML=`<span>${error.message}</span>`}}
[variant,locationField,dateField].forEach(x=>x.addEventListener('change',loadSlots));
form.addEventListener('submit',(event)=>{event.preventDefault();if(!startsAt.value)return;const selectedVariant=state.catalog?.variants.find(x=>x.id===variant.value);const selectedLocation=state.catalog?.locations.find(x=>x.id===locationField.value);sessionStorage.setItem('vetsvet_grooming_intent',JSON.stringify({version:1,variantId:variant.value,variantName:selectedVariant?.name,locationId:locationField.value,locationName:selectedLocation?.name,date:dateField.value,startsAt:startsAt.value,createdAt:new Date().toISOString()}));location.assign('/auth/?mode=client&view=register&returnTo=%2Fclient%2F%3Fbooking%3Dgrooming')});
const sections=$$('.scene'),rail=$$('.scene-rail a');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const index=Math.max(0,sections.indexOf(entry.target));rail.forEach((a,i)=>a.classList.toggle('active',i===Math.min(index,rail.length-1)))}}),{threshold:.35});sections.forEach(x=>observer.observe(x));
addEventListener('scroll',()=>{$('.progress').style.transform=`scaleX(${scrollY/(document.documentElement.scrollHeight-innerHeight)||0})`},{passive:true});
if(!matchMedia('(prefers-reduced-motion: reduce)').matches&&innerWidth>800)addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*10,y=(event.clientY/innerHeight-.5)*10;$('.hero-object').style.transform=`rotateY(${x}deg) rotateX(${-y}deg)`},{passive:true});
$$('.journey-copy li').forEach((item,index)=>setTimeout(()=>{$$('.journey-copy li').forEach(x=>x.classList.remove('active'));item.classList.add('active')},1800*(index+1)));
loadCatalog();
