import { randomUUID } from 'node:crypto';
import { DomainError } from '../core/errors';
import type { CommandMeta, ISODateTime, UUID } from '../core/types';
import { iso } from '../core/types';
import { AccessService } from '../identity/access-service';
import { AuditOutbox } from '../platform/audit-outbox';
import { SurgeryService } from '../surgery/surgery-service';

export type AnesthesiaState = 'DRAFT' | 'ACTIVE' | 'RECOVERY' | 'CLOSED';
export type VitalReading = { recordedAt: ISODateTime; heartRate?: number; respiratoryRate?: number; temperatureC?: number; spo2?: number; systolicBp?: number; note?: string };
export type AnesthesiaRecord = { id: UUID; organizationId: UUID; surgicalCaseId: UUID; petId: UUID; responsibleStaffId: UUID; state: AnesthesiaState; preAssessment?: string; protocol?: string; airway?: string; medications: Array<{ name: string; dose: string; at: ISODateTime }>; vitals: VitalReading[]; events: Array<{ note: string; at: ISODateTime }>; createdAt: ISODateTime; closedAt?: ISODateTime };

/** A separate time-oriented anesthesia record prevents mixing monitoring data between patients. */
export class AnesthesiaService {
  readonly records = new Map<UUID, AnesthesiaRecord>();
  constructor(private readonly journal: AuditOutbox, private readonly access: AccessService, private readonly surgery: SurgeryService) {}
  create(input: { surgicalCaseId: UUID; preAssessment: string; protocol: string; airway: string }, meta: CommandMeta): AnesthesiaRecord {
    this.access.require(meta.actor, 'clinical:write'); const surgicalCase = this.surgery.get(input.surgicalCaseId, meta.actor.organizationId);
    if (!['PLANNED', 'PREPARED', 'READY'].includes(surgicalCase.state) || !input.preAssessment.trim() || !input.protocol.trim() || !input.airway.trim()) throw new DomainError('CONFLICT', 'A scheduled case and complete pre-anesthetic assessment are required.');
    const now = meta.now ?? new Date(); const record: AnesthesiaRecord = { id: randomUUID(), organizationId: meta.actor.organizationId, surgicalCaseId: surgicalCase.id, petId: surgicalCase.petId, responsibleStaffId: meta.actor.userId, state: 'DRAFT', preAssessment: input.preAssessment.trim(), protocol: input.protocol.trim(), airway: input.airway.trim(), medications: [], vitals: [], events: [], createdAt: iso(now) }; this.records.set(record.id, record); this.record(meta, record, 'anesthesia.record_created', {}, now); return record;
  }
  start(recordId: UUID, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.get(recordId, meta.actor.organizationId); const surgicalCase = this.surgery.get(record.surgicalCaseId, meta.actor.organizationId); if (record.state !== 'DRAFT' || surgicalCase.state !== 'IN_PROCEDURE') throw new DomainError('CONFLICT', 'Anesthesia monitoring can only start when this patient is in the procedure.'); record.state = 'ACTIVE'; this.record(meta, record, 'anesthesia.monitoring_started', {}); return record; }
  addMedication(recordId: UUID, input: { name: string; dose: string }, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.assertActive(recordId, meta); if (!input.name.trim() || !input.dose.trim()) throw new DomainError('VALIDATION', 'Medication name and dose are required.'); record.medications.push({ name: input.name.trim(), dose: input.dose.trim(), at: iso(meta.now ?? new Date()) }); this.record(meta, record, 'anesthesia.medication_recorded', { medicationCount: record.medications.length }); return record; }
  addVitals(recordId: UUID, input: Omit<VitalReading, 'recordedAt'>, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.assertActive(recordId, meta); const values = [input.heartRate, input.respiratoryRate, input.temperatureC, input.spo2, input.systolicBp].filter((value): value is number => value !== undefined); if (!values.length || values.some((value) => !Number.isFinite(value) || value < 0)) throw new DomainError('VALIDATION', 'At least one valid non-negative vital measurement is required.'); record.vitals.push({ ...input, recordedAt: iso(meta.now ?? new Date()) }); this.record(meta, record, 'anesthesia.vitals_recorded', { vitalCount: record.vitals.length }); return record; }
  addEvent(recordId: UUID, note: string, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.assertActive(recordId, meta); if (!note.trim()) throw new DomainError('VALIDATION', 'An anesthesia event note is required.'); record.events.push({ note: note.trim(), at: iso(meta.now ?? new Date()) }); this.record(meta, record, 'anesthesia.event_recorded', { eventCount: record.events.length }); return record; }
  enterRecovery(recordId: UUID, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.get(recordId, meta.actor.organizationId); const surgicalCase = this.surgery.get(record.surgicalCaseId, meta.actor.organizationId); if (record.state !== 'ACTIVE' || surgicalCase.state !== 'RECOVERY') throw new DomainError('CONFLICT', 'The matching surgical case must enter recovery before anesthesia recovery.'); record.state = 'RECOVERY'; this.record(meta, record, 'anesthesia.recovery_started', {}); return record; }
  close(recordId: UUID, meta: CommandMeta): AnesthesiaRecord { this.access.require(meta.actor, 'clinical:write'); const record = this.get(recordId, meta.actor.organizationId); if (record.state !== 'RECOVERY') throw new DomainError('CONFLICT', 'Only a recovering anesthesia record can be closed.'); const now = meta.now ?? new Date(); record.state = 'CLOSED'; record.closedAt = iso(now); this.record(meta, record, 'anesthesia.record_closed', {}, now); return record; }
  private assertActive(recordId: UUID, meta: CommandMeta): AnesthesiaRecord { const record = this.get(recordId, meta.actor.organizationId); if (record.state !== 'ACTIVE') throw new DomainError('CONFLICT', 'Anesthesia monitoring is not active for this record.'); return record; }
  private get(recordId: UUID, organizationId: UUID): AnesthesiaRecord { const record = this.records.get(recordId); if (!record || record.organizationId !== organizationId) throw new DomainError('NOT_FOUND', 'Anesthesia record is not available in this organization.'); return record; }
  private record(meta: CommandMeta, record: AnesthesiaRecord, action: string, metadata: Record<string, unknown>, now = meta.now ?? new Date()): void { this.journal.record(meta, { action, aggregateType: 'AnesthesiaRecord', aggregateId: record.id, metadata }, { eventName: action, aggregateType: 'AnesthesiaRecord', aggregateId: record.id, payload: { petId: record.petId, surgicalCaseId: record.surgicalCaseId } }, now); }
}
