const staffEscape = (value) => String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
const staffKey = () => crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(16).slice(2)}`;

async function staffApi(path, method = 'GET', payload) {
  const response = await fetch(path, {
    method,
    headers: payload ? { 'content-type': 'application/json', 'idempotency-key': staffKey() } : undefined,
    body: payload ? JSON.stringify(payload) : undefined
  });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Не удалось выполнить действие.');
  return data;
}

function stateLabel(state) {
  return ({ REQUESTED: 'ожидает решения', CONFIRMED: 'подтверждено', CHECKED_IN: 'в клинике', IN_SERVICE: 'в работе', READY: 'готово', ISSUED: 'счёт выставлен', PENDING_QUOTE: 'стоимость уточняется', AWAITING_PROOF: 'ждём чек', PENDING_REVIEW: 'чек проверяется', PENDING_PAYMENT_REVIEW: 'ждём проверку оплаты', PAID: 'оплачено' })[state] || state;
}

function formatWhen(value) {
  return new Date(value).toLocaleString('ru-RU', { weekday: 'short', day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' });
}

function renderStaff(data) {
  const workspace = document.querySelector('.workspace');
  const requested = data.appointments.filter((item) => item.state === 'REQUESTED');
  const active = data.appointments.filter((item) => item.state !== 'REQUESTED');
  const next = { CONFIRMED: ['CHECK_IN', 'Отметить приход'], CHECKED_IN: ['START', 'Начать визит'], READY: ['COMPLETE', 'Завершить запись'] };
  const rows = (active.length ? active : data.appointments).map((item) => { const action = next[item.state]; return `<article class="row"><span class="time">${staffEscape(formatWhen(item.startsAt))}</span><div class="who"><h3>${staffEscape(item.pet)} · ${staffEscape(item.species)}</h3><p>${staffEscape(item.owner)} · ${staffEscape(item.service)}${item.groomingVisit?.state === 'COMPLETE' ? ' · отчёт готов' : ''}</p>${action ? `<p style="margin:8px 0 0"><button class="button" data-flow="${action[0]}" data-id="${staffEscape(item.id)}">${action[1]}</button></p>` : ''}</div><span class="chip ${item.state === 'CONFIRMED' ? 'vet' : 'wait'}">${staffEscape(stateLabel(item.state))}</span></article>`; }).join('') || '<p style="padding:18px;color:var(--muted)">На ближайшее время нет подтверждённых записей.</p>';
  const queue = requested.map((item) => { const paid = !item.consultation || item.consultation.paymentState === 'CONFIRMED'; return `<article class="task"><i class="check"></i><div><b>${staffEscape(item.pet)} · ${staffEscape(item.service)}</b><span>${staffEscape(item.owner)} · ${staffEscape(formatWhen(item.startsAt))}<br>${item.consultation ? `Оплата консультации: ${staffEscape(stateLabel(item.consultation.paymentState))}<br>Вопрос: ${staffEscape(item.consultation.question)}` : `Финансы: ${staffEscape(stateLabel(item.invoiceState))}`}</span><p style="margin:9px 0 0;display:flex;gap:7px">${paid ? `<button class="button" data-flow="CONFIRM" data-id="${staffEscape(item.id)}">Подтвердить</button>` : '<span class="chip wait">ждём проверки чека</span>'}<button class="button secondary" data-flow="CANCEL" data-id="${staffEscape(item.id)}">Отклонить</button></p></div></article>`; }).join('') || '<p style="padding:14px 0;color:var(--muted);font-size:12px">Новых запросов нет. Всё спокойно.</p>';
  const grooming = active.filter((item) => item.kind === 'GROOMING' && item.state === 'IN_SERVICE').map((item) => item.groomingVisit?.state === 'IN_PROGRESS' ? `<form class="grooming-report" data-visit="${staffEscape(item.groomingVisit.id)}" style="padding:14px 0;border-bottom:1px solid var(--line)"><b>${staffEscape(item.pet)} · отчёт для владельца</b><textarea name="report" required minlength="10" maxlength="5000" placeholder="Как прошла процедура, что важно для следующего ухода" style="width:100%;min-height:88px;margin:9px 0;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><label style="display:block;margin:0 0 9px;font-size:12px;color:var(--muted)">Следующий уход <input name="nextCareAt" type="datetime-local" style="margin-left:5px;padding:6px;border:1px solid var(--line);border-radius:6px"></label><button class="button" type="submit">Отправить отчёт</button></form>` : `<form class="grooming-start" data-appointment="${staffEscape(item.id)}" style="padding:14px 0;border-bottom:1px solid var(--line)"><b>${staffEscape(item.pet)} · подготовить уход</b><input name="preferredStyle" placeholder="Желаемый стиль" style="width:100%;margin:9px 0;padding:10px;border:1px solid var(--line);border-radius:8px"><textarea name="behaviorNotes" placeholder="Что поможет питомцу чувствовать себя спокойно" style="width:100%;min-height:62px;margin:0 0 9px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><input name="recipeTitle" placeholder="Название рецепта ухода" style="width:100%;margin:0 0 9px;padding:10px;border:1px solid var(--line);border-radius:8px"><input name="recipeSteps" placeholder="Шаги через запятую: мытьё, сушка, оформление" style="width:100%;margin:0 0 9px;padding:10px;border:1px solid var(--line);border-radius:8px"><button class="button" type="submit">Открыть визит груминга</button></form>`).join('') || '<p style="padding:14px 0;color:var(--muted);font-size:12px">Сейчас нет груминг-визитов в работе.</p>';
  const consultationWork = active.filter((item) => item.kind === 'CONSULTATION' && item.state === 'IN_SERVICE' && item.consultation).map((item) => `<form class="consultation-response" data-consultation="${staffEscape(item.consultation.id)}" style="padding:14px 0;border-bottom:1px solid var(--line)"><b>${staffEscape(item.pet)} · ответ владельцу</b><p style="margin:6px 0;color:var(--muted);font-size:12px;line-height:1.45">${staffEscape(item.consultation.question)}</p><textarea name="response" required minlength="20" maxlength="6000" placeholder="Вывод специалиста, дальнейшие шаги и признаки, при которых нужна очная помощь" style="width:100%;min-height:110px;margin:4px 0 9px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><button class="button" type="submit">Сохранить ответ</button></form>`).join('') || '<p style="padding:14px 0;color:var(--muted);font-size:12px">Сейчас нет консультаций в работе.</p>';
  const clinicalWork = active.filter((item) => item.kind === 'VETERINARY' && item.state === 'IN_SERVICE' && !item.encounter).map((item) => `<form class="clinical-encounter" data-appointment="${staffEscape(item.id)}" style="padding:14px 0;border-bottom:1px solid var(--line)"><b>${staffEscape(item.pet)} · клинический приём</b><input name="reason" required minlength="3" maxlength="500" placeholder="Причина обращения" style="width:100%;margin:9px 0;padding:10px;border:1px solid var(--line);border-radius:8px"><textarea name="subjective" maxlength="4000" placeholder="S · жалобы и наблюдения владельца" style="width:100%;min-height:64px;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><textarea name="objective" maxlength="4000" placeholder="O · объективные данные осмотра" style="width:100%;min-height:64px;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><textarea name="assessment" required minlength="10" maxlength="4000" placeholder="A · клиническая оценка" style="width:100%;min-height:70px;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><textarea name="plan" required minlength="10" maxlength="4000" placeholder="P · план лечения и наблюдения" style="width:100%;min-height:78px;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"></textarea><input name="medicationName" maxlength="240" placeholder="Препарат (необязательно)" style="width:100%;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"><input name="instructions" maxlength="1000" placeholder="Схема применения" style="width:100%;margin:0 0 8px;padding:10px;border:1px solid var(--line);border-radius:8px"><label style="display:block;margin:0 0 9px;font-size:12px;color:var(--muted)">Контрольный приём <input name="followUpAt" type="datetime-local" style="margin-left:5px;padding:6px;border:1px solid var(--line);border-radius:6px"></label><button class="button" type="submit">Финализировать приём</button></form>`).join('') || '<p style="padding:14px 0;color:var(--muted);font-size:12px">Сейчас нет клинических приёмов в работе.</p>';
  workspace.innerHTML = `<header class="top"><div><h1>Рабочее место VetSvet</h1><p>Живая очередь, расписание и решения команды · роль: ${staffEscape(data.account.role)}</p></div><div class="command">Сначала статус, потом действие <kbd>⌘</kbd></div></header><div class="board"><section class="card schedule"><div class="card-head"><h2>Расписание</h2><span class="count">${active.length}</span></div>${rows}</section><section class="card"><div class="card-head"><h2>Очередь записи</h2><span class="count">${requested.length}</span></div><div class="tasks">${queue}</div></section><section class="card"><div class="card-head"><h2>Клинический контур</h2><span class="count">SOAP</span></div><div class="patient">${clinicalWork}</div></section><section class="card"><div class="card-head"><h2>Груминг в работе</h2><span class="count">live</span></div><div class="patient">${grooming}</div></section><section class="card"><div class="card-head"><h2>Консультации</h2><span class="count">live</span></div><div class="patient">${consultationWork}</div></section></div>`;
  workspace.querySelectorAll('button[data-flow]').forEach((button) => button.addEventListener('click', async () => { button.disabled = true; try { await staffApi(`/api/v1/staff/appointments/${encodeURIComponent(button.dataset.id)}`, 'PATCH', { action: button.dataset.flow }); await loadStaff(); } catch (error) { window.alert(error.message); button.disabled = false; } }));
  workspace.querySelectorAll('form.grooming-start').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(form); const recipeSteps = String(values.get('recipeSteps') ?? '').split(',').map((item) => item.trim()).filter(Boolean); try { await staffApi('/api/v1/staff/grooming/visits', 'POST', { appointmentId: form.dataset.appointment, preferredStyle: values.get('preferredStyle'), behaviorNotes: values.get('behaviorNotes'), recipeTitle: values.get('recipeTitle'), recipeSteps }); await loadStaff(); } catch (error) { window.alert(error.message); } }));
  workspace.querySelectorAll('form.grooming-report').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(form); try { await staffApi(`/api/v1/staff/grooming/visits/${encodeURIComponent(form.dataset.visit)}`, 'PATCH', { report: values.get('report'), nextCareAt: values.get('nextCareAt') || undefined }); await loadStaff(); } catch (error) { window.alert(error.message); } }));
  workspace.querySelectorAll('form.consultation-response').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(form); try { await staffApi(`/api/v1/staff/consultations/${encodeURIComponent(form.dataset.consultation)}`, 'PATCH', { response: values.get('response') }); await loadStaff(); } catch (error) { window.alert(error.message); } }));
  workspace.querySelectorAll('form.clinical-encounter').forEach((form) => form.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(form); const medicationName = String(values.get('medicationName') || '').trim(); const instructions = String(values.get('instructions') || '').trim(); try { await staffApi('/api/v1/staff/clinical/encounters', 'POST', { appointmentId: form.dataset.appointment, reason: values.get('reason'), subjective: values.get('subjective'), objective: values.get('objective'), assessment: values.get('assessment'), plan: values.get('plan'), prescriptions: medicationName && instructions ? [{ medicationName, instructions }] : [], followUpAt: values.get('followUpAt') || undefined }); await loadStaff(); } catch (error) { window.alert(error.message); } }));
}

async function loadStaff() {
  const me = await staffApi('/api/v1/auth/me');
  if (me.account.mode !== 'STAFF') { location.assign('/client/'); return; }
  renderStaff(await staffApi('/api/v1/staff/dashboard'));
}

loadStaff().catch(() => location.assign('/auth/?mode=staff'));
