import { randomUUID } from 'node:crypto';
import { DomainError } from '../core/errors';
import type { CommandMeta, ISODateTime, UUID } from '../core/types';
import { iso } from '../core/types';
import { AccessService } from '../identity/access-service';
import { AuditOutbox } from '../platform/audit-outbox';

export type StaffProfile = { id: UUID; organizationId: UUID; userId: UUID; employmentState: 'ACTIVE' | 'ON_LEAVE' | 'INACTIVE'; specialties: string[]; locationIds: UUID[]; createdAt: ISODateTime };
export type Credential = { id: UUID; organizationId: UUID; userId: UUID; competency: string; certificateNumber?: string; expiresAt?: ISODateTime; permittedProcedureCodes: string[]; state: 'ACTIVE' | 'REVOKED'; createdAt: ISODateTime };

/** Role-based access answers “may this user enter”; competency answers “may this person perform this work today”. */
export class CompetencyService {
  readonly profiles = new Map<UUID, StaffProfile>(); readonly credentials = new Map<UUID, Credential>();
  constructor(private readonly journal: AuditOutbox, private readonly access: AccessService) {}
  upsertProfile(input: { userId: UUID; employmentState: StaffProfile['employmentState']; specialties?: string[]; locationIds?: UUID[] }, meta: CommandMeta): StaffProfile { this.access.require(meta.actor, 'organization:manage'); const existing = [...this.profiles.values()].find((item) => item.organizationId === meta.actor.organizationId && item.userId === input.userId); if (existing) { existing.employmentState = input.employmentState; existing.specialties = [...new Set((input.specialties ?? []).map((value) => value.trim()).filter(Boolean))]; existing.locationIds = [...new Set(input.locationIds ?? [])]; return existing; } const now = meta.now ?? new Date(); const profile: StaffProfile = { id: randomUUID(), organizationId: meta.actor.organizationId, userId: input.userId, employmentState: input.employmentState, specialties: [...new Set((input.specialties ?? []).map((value) => value.trim()).filter(Boolean))], locationIds: [...new Set(input.locationIds ?? [])], createdAt: iso(now) }; this.profiles.set(profile.id, profile); return profile; }
  grantCredential(input: { userId: UUID; competency: string; certificateNumber?: string; expiresAt?: ISODateTime; permittedProcedureCodes?: string[] }, meta: CommandMeta): Credential { this.access.require(meta.actor, 'organization:manage'); if (!input.competency.trim() || (input.expiresAt && Number.isNaN(new Date(input.expiresAt).valueOf()))) throw new DomainError('VALIDATION', 'Competency and a valid expiry date are required.'); const now = meta.now ?? new Date(); const credential: Credential = { id: randomUUID(), organizationId: meta.actor.organizationId, userId: input.userId, competency: input.competency.trim(), certificateNumber: input.certificateNumber?.trim() || undefined, expiresAt: input.expiresAt, permittedProcedureCodes: [...new Set((input.permittedProcedureCodes ?? []).map((value) => value.trim()).filter(Boolean))], state: 'ACTIVE', createdAt: iso(now) }; this.credentials.set(credential.id, credential); this.journal.record(meta, { action: 'credential.granted', aggregateType: 'Credential', aggregateId: credential.id, metadata: { competency: credential.competency } }, { eventName: 'credential.granted', aggregateType: 'Credential', aggregateId: credential.id, payload: { userId: credential.userId } }, now); return credential; }
  assertEligible(input: { userId: UUID; competency: string; procedureCode?: string; locationId?: UUID; at?: Date }, organizationId: UUID): void { const profile = [...this.profiles.values()].find((item) => item.organizationId === organizationId && item.userId === input.userId); if (!profile || profile.employmentState !== 'ACTIVE' || (input.locationId && !profile.locationIds.includes(input.locationId))) throw new DomainError('FORBIDDEN', 'Staff member is not active or assigned to this location.'); const now = input.at ?? new Date(); const credential = [...this.credentials.values()].find((item) => item.organizationId === organizationId && item.userId === input.userId && item.competency === input.competency && item.state === 'ACTIVE' && (!item.expiresAt || new Date(item.expiresAt) >= now) && (!input.procedureCode || item.permittedProcedureCodes.includes(input.procedureCode))); if (!credential) throw new DomainError('FORBIDDEN', 'A current required competency is not available for this staff member.'); }
  expiringWithin(organizationId: UUID, days: number, now = new Date()): Credential[] { const deadline = new Date(now); deadline.setUTCDate(deadline.getUTCDate() + days); return [...this.credentials.values()].filter((item) => item.organizationId === organizationId && item.state === 'ACTIVE' && item.expiresAt && new Date(item.expiresAt) >= now && new Date(item.expiresAt) <= deadline); }
}
