import { OwnerPetService } from './clients/owner-pet-service';
import { OrganizationService } from './organizations/organization-service';
import { AuditOutbox } from './platform/audit-outbox';
import { AccessService } from './identity/access-service';
import { CatalogService } from './catalog/catalog-service';
import { BookingService } from './booking/booking-service';
import { FinanceService } from './finance/finance-service';
import { GroomingService } from './grooming/grooming-service';
import { TriageService } from './triage/triage-service';
import { ConsultationService } from './consultation/consultation-service';
import { ClinicalService } from './clinical/clinical-service';
import { FileService } from './files/file-service';
import { DocumentService } from './documents/document-service';
import { CarePlanService } from './care/care-plan-service';
import { NotificationPreferenceService } from './notifications/notification-preference-service';
import { TimelineService } from './timeline/timeline-service';
import { OperationsService } from './operations/operations-service';
import { InventoryService } from './inventory/inventory-service';
import { HospitalService } from './hospital/hospital-service';
import { ReferralService } from './referrals/referral-service';
import { SupportService } from './support/support-service';
import { GrowthService } from './growth/growth-service';
import { AnalyticsService } from './analytics/analytics-service';
import { KnowledgeService } from './knowledge/knowledge-service';
import { FeatureFlagService } from './flags/feature-flag-service';
import { PassportService } from './passport/passport-service';
import { PrivacyService } from './privacy/privacy-service';
import { AiDraftService } from './ai/ai-draft-service';
import { WaitlistService } from './waitlist/waitlist-service';
import { PreventiveService } from './preventive/preventive-service';
import { DiagnosticService } from './diagnostics/diagnostic-service';
import { ReportingService } from './reporting/reporting-service';
import { AuthService } from './auth/auth-service';
import { InboxService } from './communication/inbox-service';
import { SurgeryService } from './surgery/surgery-service';
import { AnesthesiaService } from './anesthesia/anesthesia-service';
import { DentalService } from './dental/dental-service';
import { EquipmentService } from './equipment/equipment-service';
import { PhysicalIdentityService } from './identity/physical-identity-service';
import { SpecimenService } from './diagnostics/specimen-service';
import { ProcurementService } from './procurement/procurement-service';
import { PrintService } from './printing/print-service';
import { ChecklistService } from './sop/checklist-service';
import { CompetencyService } from './staff/competency-service';
import { PrecheckService } from './checkin/precheck-service';

/** Composition root. Replace in-memory persistence with PostgreSQL repositories
 * without changing domain contracts or client-facing behavior. */
export function createFoundation() {
  const journal = new AuditOutbox();
  const access = new AccessService();
  const organizations = new OrganizationService(journal, access);
  const ownerPets = new OwnerPetService(journal, access);
  const catalog = new CatalogService(journal, access);
  const booking = new BookingService(journal, access, catalog, ownerPets);
  const finance = new FinanceService(journal, access, booking, catalog);
  const grooming = new GroomingService(journal, access, booking, catalog);
  const triage = new TriageService(journal, access);
  const consultations = new ConsultationService(journal, access, booking, catalog, finance);
  const clinical = new ClinicalService(journal, access, booking);
  const files = new FileService(journal, access);
  const documents = new DocumentService(journal, access);
  const carePlans = new CarePlanService(journal, access, booking);
  const notificationPreferences = new NotificationPreferenceService(journal, access);
  const timeline = new TimelineService(journal);
  const operations = new OperationsService(journal, access);
  const inventory = new InventoryService(journal, access);
  const hospital = new HospitalService(journal, access, booking);
  const referrals = new ReferralService(journal, access);
  const support = new SupportService(journal, access);
  const growth = new GrowthService(journal, access);
  const analytics = new AnalyticsService();
  const knowledge = new KnowledgeService(journal, access);
  const flags = new FeatureFlagService(access);
  const passport = new PassportService(journal, access, booking);
  const privacy = new PrivacyService(journal, access);
  const ai = new AiDraftService(journal, access);
  const waitlist = new WaitlistService(journal, access, booking);
  const preventive = new PreventiveService(journal, access, booking);
  const diagnostics = new DiagnosticService(journal, access, booking);
  const reporting = new ReportingService(booking, finance);
  const auth = new AuthService();
  const inbox = new InboxService(journal, access);
  const competencies = new CompetencyService(journal, access);
  const prechecks = new PrecheckService(journal, access, booking);
  const surgery = new SurgeryService(journal, access, booking, competencies);
  const anesthesia = new AnesthesiaService(journal, access, surgery);
  const dental = new DentalService(journal, access, booking);
  const equipment = new EquipmentService(journal, access, organizations);
  const physicalIdentities = new PhysicalIdentityService(journal, access);
  const specimens = new SpecimenService(journal, access, diagnostics, physicalIdentities);
  const procurement = new ProcurementService(journal, access, inventory);
  const printing = new PrintService(journal, access);
  const checklists = new ChecklistService(journal, access);
  return { journal, access, organizations, ownerPets, catalog, booking, finance, grooming, triage, consultations, clinical, files, documents, carePlans, notificationPreferences, timeline, operations, inventory, hospital, referrals, support, growth, analytics, knowledge, flags, passport, privacy, ai, waitlist, preventive, diagnostics, reporting, auth, inbox, surgery, anesthesia, dental, equipment, physicalIdentities, specimens, procurement, printing, checklists, competencies, prechecks };
}
