import { randomUUID } from 'node:crypto';
import { DomainError } from '../core/errors';
import type { CommandMeta, ISODateTime, UUID } from '../core/types';
import { iso } from '../core/types';
import { AccessService } from '../identity/access-service';
import { InventoryService } from '../inventory/inventory-service';
import { AuditOutbox } from '../platform/audit-outbox';

export type Supplier = { id: UUID; organizationId: UUID; name: string; contactEmail?: string; state: 'ACTIVE' | 'INACTIVE'; createdAt: ISODateTime };
export type PurchaseOrderLine = { id: UUID; itemId: UUID; orderedQuantity: number; receivedQuantity: number; unitPriceMinor?: number; discrepancyNote?: string };
export type PurchaseOrder = { id: UUID; organizationId: UUID; supplierId: UUID; locationId: UUID; state: 'DRAFT' | 'APPROVED' | 'ORDERED' | 'PARTIALLY_RECEIVED' | 'RECEIVED' | 'CANCELLED'; lines: PurchaseOrderLine[]; createdAt: ISODateTime; approvedAt?: ISODateTime; orderedAt?: ISODateTime; receivedAt?: ISODateTime };

/** Purchasing is a controlled receiving workflow; stock only changes on accepted receipt. */
export class ProcurementService {
  readonly suppliers = new Map<UUID, Supplier>(); readonly orders = new Map<UUID, PurchaseOrder>();
  constructor(private readonly journal: AuditOutbox, private readonly access: AccessService, private readonly inventory: InventoryService) {}
  createSupplier(input: { name: string; contactEmail?: string }, meta: CommandMeta): Supplier { this.access.require(meta.actor, 'finance:write'); if (!input.name.trim()) throw new DomainError('VALIDATION', 'Supplier name is required.'); const now = meta.now ?? new Date(); const supplier: Supplier = { id: randomUUID(), organizationId: meta.actor.organizationId, name: input.name.trim(), contactEmail: input.contactEmail?.trim() || undefined, state: 'ACTIVE', createdAt: iso(now) }; this.suppliers.set(supplier.id, supplier); this.record(meta, 'supplier.created', 'Supplier', supplier.id, {}); return supplier; }
  createOrder(input: { supplierId: UUID; locationId: UUID; lines: Array<{ itemId: UUID; quantity: number; unitPriceMinor?: number }> }, meta: CommandMeta): PurchaseOrder {
    this.access.require(meta.actor, 'finance:write'); const supplier = this.suppliers.get(input.supplierId); if (!supplier || supplier.organizationId !== meta.actor.organizationId || supplier.state !== 'ACTIVE') throw new DomainError('NOT_FOUND', 'An active supplier is required.'); if (!input.lines.length) throw new DomainError('VALIDATION', 'Purchase order requires at least one line.');
    const lines = input.lines.map((line) => { const item = this.inventory.items.get(line.itemId); if (!item || item.organizationId !== meta.actor.organizationId || !Number.isSafeInteger(line.quantity) || line.quantity < 1 || (line.unitPriceMinor !== undefined && (!Number.isSafeInteger(line.unitPriceMinor) || line.unitPriceMinor < 0))) throw new DomainError('VALIDATION', 'Each purchase line requires an available item, positive quantity and valid price.'); return { id: randomUUID(), itemId: line.itemId, orderedQuantity: line.quantity, receivedQuantity: 0, unitPriceMinor: line.unitPriceMinor }; });
    if (new Set(lines.map((line) => line.itemId)).size !== lines.length) throw new DomainError('CONFLICT', 'An inventory item may appear only once in a purchase order.'); const now = meta.now ?? new Date(); const order: PurchaseOrder = { id: randomUUID(), organizationId: meta.actor.organizationId, supplierId: supplier.id, locationId: input.locationId, state: 'DRAFT', lines, createdAt: iso(now) }; this.orders.set(order.id, order); this.record(meta, 'purchase_order.created', 'PurchaseOrder', order.id, { lineCount: lines.length }); return order;
  }
  approve(orderId: UUID, meta: CommandMeta): PurchaseOrder { const order = this.transition(orderId, 'DRAFT', 'APPROVED', meta); order.approvedAt = iso(meta.now ?? new Date()); this.record(meta, 'purchase_order.approved', 'PurchaseOrder', order.id, {}); return order; }
  order(orderId: UUID, meta: CommandMeta): PurchaseOrder { const order = this.transition(orderId, 'APPROVED', 'ORDERED', meta); order.orderedAt = iso(meta.now ?? new Date()); this.record(meta, 'purchase_order.ordered', 'PurchaseOrder', order.id, {}); return order; }
  receive(orderId: UUID, input: { lines: Array<{ lineId: UUID; quantity: number; discrepancyNote?: string }> }, meta: CommandMeta): PurchaseOrder {
    this.access.require(meta.actor, 'finance:write'); const order = this.get(orderId, meta.actor.organizationId); if (!['ORDERED', 'PARTIALLY_RECEIVED'].includes(order.state) || !input.lines.length) throw new DomainError('CONFLICT', 'Only an ordered purchase order can be received.');
    const submitted = new Set<string>(); for (const receipt of input.lines) { if (submitted.has(receipt.lineId) || !Number.isSafeInteger(receipt.quantity) || receipt.quantity < 1) throw new DomainError('VALIDATION', 'Each received purchase line must be unique with a positive quantity.'); submitted.add(receipt.lineId); const line = order.lines.find((item) => item.id === receipt.lineId); if (!line || receipt.quantity > line.orderedQuantity - line.receivedQuantity) throw new DomainError('CONFLICT', 'Received quantity cannot exceed the remaining ordered quantity.'); line.receivedQuantity += receipt.quantity; line.discrepancyNote = receipt.discrepancyNote?.trim() || line.discrepancyNote; this.inventory.move({ itemId: line.itemId, locationId: order.locationId, quantity: receipt.quantity, direction: 'RECEIPT', reason: `Purchase order ${order.id}` }, { ...meta, idempotencyKey: `${meta.idempotencyKey}:stock:${line.id}` }); }
    const complete = order.lines.every((line) => line.receivedQuantity === line.orderedQuantity); order.state = complete ? 'RECEIVED' : 'PARTIALLY_RECEIVED'; if (complete) order.receivedAt = iso(meta.now ?? new Date()); this.record(meta, 'purchase_order.receipt_recorded', 'PurchaseOrder', order.id, { complete }); return order;
  }
  private transition(orderId: UUID, from: PurchaseOrder['state'], to: PurchaseOrder['state'], meta: CommandMeta): PurchaseOrder { this.access.require(meta.actor, 'finance:write'); const order = this.get(orderId, meta.actor.organizationId); if (order.state !== from) throw new DomainError('CONFLICT', 'Purchase order transition is invalid.'); order.state = to; return order; }
  private get(orderId: UUID, organizationId: UUID): PurchaseOrder { const order = this.orders.get(orderId); if (!order || order.organizationId !== organizationId) throw new DomainError('NOT_FOUND', 'Purchase order is not available in this organization.'); return order; }
  private record(meta: CommandMeta, action: string, aggregateType: string, aggregateId: UUID, metadata: Record<string, unknown>): void { this.journal.record(meta, { action, aggregateType, aggregateId, metadata }, { eventName: action, aggregateType, aggregateId, payload: {} }); }
}
